// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/saevws.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gibbs_cpp
Rcpp::List gibbs_cpp(const arma::vec& y, const arma::vec& s2, const arma::mat& X, const arma::mat& Z, const arma::vec& df, const Rcpp::List& init, const Rcpp::List& control, const Rcpp::List& fixed);
RcppExport SEXP _saevws_gibbs_cpp(SEXP ySEXP, SEXP s2SEXP, SEXP XSEXP, SEXP ZSEXP, SEXP dfSEXP, SEXP initSEXP, SEXP controlSEXP, SEXP fixedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type init(initSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type control(controlSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fixed(fixedSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_cpp(y, s2, X, Z, df, init, control, fixed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_saevws_gibbs_cpp", (DL_FUNC) &_saevws_gibbs_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_saevws(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
