# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbs_joint_cpp <- function(y, s2, X, Z, df, init, control, fixed) {
    .Call(`_saevws_gibbs_joint_cpp`, y, s2, X, Z, df, init, control, fixed)
}

gibbs_mismatch_cpp <- function(y, sigma, X, init, control, fixed) {
    .Call(`_saevws_gibbs_mismatch_cpp`, y, sigma, X, init, control, fixed)
}

