# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbs_cpp <- function(y, s2, X, Z, df, init, control, fixed) {
    .Call(`_saevws_gibbs_cpp`, y, s2, X, Z, df, init, control, fixed)
}

